### ISSUE TITLE
Implement Buttons

### ISSUE THREAD

**Issue by JulianusIV** [JulianusIV/LathBot#21]
Further ideas are welcome in the comments

- [x] warn rule select
- [x] (experimentally) warn points amount
- [x] mute "are you sure about that"
- [x] kick "are you sure about that"
- [x] ban "are you sure about that"

**Comment by Femkeuwu** [comment]
yo fuckshit here is your github suggestion: When muting or banning a user, have lathbot tell you if you really want to mute/ban said person. Because most of the time staff will be using ID's, so something as simple as the chat scrolling can mess up which user ID you copy, which can then lead to all levels being removed upon a ban. 



_i hope you're happy cunt_

**Comment by JulianusIV** [comment]
This issue will be considered closed, but kept open incase of further ideas
